/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from '@latticexyz/recs'

export function defineContractComponents(world: World) {
  return {
    Attributes: (() => {
      const name = 'Attributes'
      return defineComponent(
        world,
        {
          points: RecsType.Number,
          str: RecsType.Number,
          dex: RecsType.Number,
          con: RecsType.Number,
          int: RecsType.Number,
          wis: RecsType.Number,
          cha: RecsType.Number,
          str_modifier: RecsType.Number,
          dex_modifier: RecsType.Number,
          con_modifier: RecsType.Number,
          int_modifier: RecsType.Number,
          wis_modifier: RecsType.Number,
          cha_modifier: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      )
    })(),
    Stats: (() => {
      const name = 'Stats'
      return defineComponent(
        world,
        {
          ac: RecsType.Number,
          damage_dice: RecsType.Number,
          hp: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      )
    })(),
    Position: (() => {
      const name = 'Position'
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      )
    })(),
    Counter: (() => {
      const name = 'Counter'
      return defineComponent(
        world,
        {
          count: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      )
    })(),
    Quest: (() => {
      const name = 'Quest'
      return defineComponent(
        world,
        {
          quest_state: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      )
    })(),
  }
}
